<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { showFailToast } from 'vant'
import AppTabbar from '@/components/AppTabbar.vue'
import { useAuthStore } from '@/stores/auth'
import { useFamilyStore } from '@/stores/family'
import { useSmokingStore } from '@/stores/smoking'
import { useDisplayMode, type DisplayMode } from '@/composables/useDisplayMode'

const authStore=useAuthStore();const familyStore=useFamilyStore();const smokingStore=useSmokingStore();const router=useRouter();const loggingOut=ref(false);const loading=ref(true)
const devToolsEnabled=import.meta.env.VITE_ENABLE_DEV_TOOLS==='true'
const {displayMode,setDisplayMode}=useDisplayMode()
function changeDisplayMode(mode:DisplayMode){setDisplayMode(mode);if(mode==='desktop')void router.replace('/dashboard')}
onMounted(async()=>{try{await familyStore.initializeFamily();if(familyStore.isQuitter)await smokingStore.ensureSmokingProfileLoaded()}catch(error:unknown){console.error('加载个人资料失败',error);showFailToast('加载个人资料失败')}finally{loading.value=false}})
async function logout(){if(loggingOut.value)return;loggingOut.value=true;try{await authStore.logout();await router.replace('/login')}catch(error:unknown){console.error('退出登录失败',error);showFailToast('退出失败，请稍后再试')}finally{loggingOut.value=false}}
</script>

<template><main class="page shell"><h1 class="page-title">我的</h1><div v-if="loading" class="state"><van-loading size="20"/> 正在加载…</div><template v-else><section class="card account"><span class="muted">昵称</span><strong>{{familyStore.currentMember?.nickname??'家庭成员'}}</strong><span class="muted">{{authStore.user?.email??'未提供邮箱'}}</span></section><section class="card family-info"><h2>家庭信息</h2><van-cell-group inset><van-cell title="家庭" :value="familyStore.currentFamily?.name??'未加入'"/><van-cell title="身份" :value="familyStore.isQuitter?'戒烟者':'支持者'"/></van-cell-group></section><section class="card display-settings"><div><h2>显示模式</h2><span>自动模式会根据屏幕宽度切换</span></div><div class="display-options"><button v-for="mode in (['auto','mobile','desktop'] as DisplayMode[])" :key="mode" :class="{active:displayMode===mode}" @click="changeDisplayMode(mode)">{{mode==='auto'?'自动':mode==='mobile'?'手机':'桌面'}}</button></div></section><section v-if="familyStore.isQuitter" class="card settings"><h2>戒烟设置</h2><van-cell-group v-if="smokingStore.smokingProfile" inset><van-cell title="开始日期" :value="smokingStore.smokingProfile.quitStartDate"/><van-cell title="原每日吸烟量" :value="`${smokingStore.smokingProfile.baselineDailyCigarettes} 支`"/><van-cell title="每包支数" :value="`${smokingStore.smokingProfile.cigarettesPerPack} 支`"/><van-cell title="每包价格" :value="`¥${smokingStore.smokingProfile.pricePerPack.toFixed(2)}`"/></van-cell-group><van-button block plain round type="primary" @click="router.push({path:'/setup',query:{edit:'1'}})">编辑戒烟设置</van-button></section><section v-if="devToolsEnabled&&familyStore.isQuitter" class="card dev-entry"><van-cell title="测试工具" label="生成历史打卡数据" icon="setting-o" is-link @click="router.push('/dev')"/></section></template><van-button class="logout" plain type="danger" round block :loading="loggingOut" @click="logout">退出登录</van-button><AppTabbar/></main></template>
<style scoped>.shell{max-width:520px;margin:auto}.account{display:flex;flex-direction:column;gap:7px;margin-bottom:14px}.family-info,.settings,.display-settings{margin-bottom:14px}.family-info h2,.settings h2,.display-settings h2{font-size:18px;margin:0 0 12px}.van-cell-group{margin:0 0 16px}.display-settings>div:first-child{display:flex;align-items:baseline;justify-content:space-between}.display-settings>div:first-child span{color:var(--text-muted);font-size:11px}.display-options{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:4px;border-radius:13px;background:#f0f3f1}.display-options button{border:0;border-radius:10px;padding:9px;background:transparent;color:#748078}.display-options button.active{background:#fff;color:var(--green-700);box-shadow:0 3px 10px rgba(25,55,43,.08);font-weight:700}.dev-entry{margin-bottom:14px;padding:7px}.dev-entry .van-cell{border-radius:14px}.logout{margin-top:18px}.state{display:flex;gap:8px;justify-content:center;padding:70px;color:#8b95a5}</style>
